### ISSUE TITLE
Memory management after compression finishes

### ISSUE THREAD

**Issue by shauryapatel1995** [NVIDIA/nvcomp#10]
According to the benchmarks our input is 400mb and the compressed size is 15mb? Do we free the rest of the output space or do we have to copy the memory and then perform an explicit free on the output space? 
Looking forward to hearing from you!

**Comment by nv-dlasalle** [comment]
@shauryapatel1995 You have three basic options:
1. Copy the compressed data to another location as you suggest (a smaller GPU allocation, host memory, etc.).
2. Re-use the left over space in the buffer for other operations.
3. Use the memory management APIs introduced in 10.2 to change the size of the allocation:
https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__VA.html#group__CUDA__VA

**Comment by shauryapatel1995** [comment]
Hi @nv-dlasalle, thanks for the response. Just a quick follow up, does the compression not support float datatypes at the moment?
