### ISSUE TITLE
[FEA] Static library builds for nvCOMP

### ISSUE THREAD

**Issue by VasuAgrawal** [NVIDIA/nvcomp#103]
**Is your feature request related to a problem? Please describe.**
I'd like to deploy a statically built binary which depends on `nvCOMP` on both Windows and Linux. Unfortunately, the provided artifacts in [the downloads](https://developer.nvidia.com/nvcomp-download) for Windows / Linux only contain dynamic libraries (`nvcomp.dll` & corresponding _import lib_ `nvcomp.lib` on Windows, `libnvcomp.so` on Linux). This makes it impossible to build and deploy a fully static binary.

**Describe the solution you'd like**
I'd appreciate it if static library targets (`nvcomp.lib` on Windows, `libnvcomp.a` on Linux) could be provided. Note that the requested _static library_ `nvcomp.lib` for Windows [is different than](https://stackoverflow.com/questions/8019464/a-static-library-vs-an-import-library-on-the-windows-platform) the _import lib_. The _import lib_ on its own is not sufficient for a fully static build, as it'll just add a dependency on the `nvcomp.dll` for you (and load it properly).

**Describe alternatives you've considered**
On Windows, it [doesn't seem possible](https://stackoverflow.com/questions/2576910/how-to-convert-a-dynamic-dll-to-static-lib) to convert a dynamic library to a static library. On Linux, it seems there _may_ be some hacky solutions, but no one-size-fits-all tool. I've also considered using an older version of the library, when all of the source was provided, to just build the static version myself, but I'd really prefer using the latest and greatest.

**Additional context**
N/A

**Comment by naveenaero** [comment]
I am closing this issue as there is another newer ticket opened after we launched static builds with nvCOMP v4.0
