### ISSUE TITLE
Questions about cascaded compression

### ISSUE THREAD

**Issue by felipeblazing** [NVIDIA/nvcomp#11]
Is my understanding correct that the only algorithms that can currently be cascaded are RLE, Delta, and Bitpacking?

Is there plans to add dictionary and other algorithms?

Right now it seems you can't really specify how to compose the different schemes just specify the number of rles and deltas to conduct and whethe or not to perform bit packing.  Is there a plan of being able to compose these more specificially where I could specify something like do an RLE , delta encode the run values , rle encode the run lengths etc. Where we can create a tree of compression as opposed to just specifing the numbers of types to apply a compressor?

**Comment by nv-dlasalle** [comment]
You are correct, currently only RLE, Delta, and BitPacking are supported by the cascaded scheme, and their order is fixed based on the number of each.

Adding more compressions layers, and allowing for composing those layers in a an arbitrary tree, is something we hope to add in the future, but is not planned for the next release.

**Comment by nsakharnykh** [comment]
@felipeblazing can this be closed now? I think you created other issues to track various suggested enhancements #17 #18
