### ISSUE TITLE
CPU compression/decompression implementations?

### ISSUE THREAD

**Issue by eglaser77** [NVIDIA/nvcomp#12]
Hi - are there CPU implementations available for compression/decompression? I.e. can I compress some data on the CPU, then copy the compressed data to the GPU and decompress it there? And vice-versa?

**Comment by nv-dlasalle** [comment]
At this point we do not support CPU compression/decompression.

**Comment by eglaser77** [comment]
Thanks for the update - is this on the roadmap at all? And if so any idea on the estimated timeframe?

**Comment by nv-dlasalle** [comment]
It is something we are aware of, but it is not currently on our road-map.

**Comment by nv-dlasalle** [comment]
@eglaser77 The 2.0 interface support compressing and decompressing raw LZ4 blocks (but not LZ4 frames), which is compatible with CPU based implementations.

See https://github.com/NVIDIA/nvcomp/blob/main/examples/lz4_cpu_compression.cu for an example.
