### ISSUE TITLE
GPU compression error

### ISSUE THREAD

**Issue by shauryapatel1995** [NVIDIA/nvcomp#13]
I am trying to run to run compression on an integer array of size 4096 but getting an error for both LZ4 and Cascaded compression.
Here is an example of the code.

```
uint32_t * uncompressed_data;
        cudaMalloc(reinterpret_cast<void**>(&uncompressed_data),sizeof(uint32_t)*4096);
        size_t free_mem, total;
        cudaMemGetInfo(&free_mem, &total);
        cout << "Free memory is: " << free_mem << " total memory is: " << total << std::endl;

        int uncompressed_count = 4096;

        nvcomp::LZ4Compressor<uint32_t> compressor(
        uncompressed_data, uncompressed_count, 1);
        const size_t temp_size = compressor.get_temp_size();

        void * temp_space;
        cudaMalloc(&temp_space, temp_size);

        size_t output_size = compressor.get_max_output_size(
    temp_space, temp_size);

        void * output_space;
        cudaMalloc(&output_space, output_size);
size_t output_size = compressor.get_max_output_size(
    temp_space, temp_size);

        void * output_space;
        cudaMalloc(&output_space, output_size);


        cudaStream_t stream;

cudaError_t cudaErr = cudaStreamCreate(&stream);
        nvcompError_t status;
compressor.compress_async(temp_space,
    temp_size, output_space, &output_size, stream);
```

The error is 
```
Free memory is: 140729606464880 total memory is: 94521694280424
Failed to get temp size: Failed to get space for cub inclusive sub: 101
terminate called after throwing an instance of 'nvcomp::NVCompException'
  what():  GetTempSize failed : code=1000.
Aborted (core dumped)
```

Facing a similar error with Cascaded compression with error code 10. Any help would be appreciated.

**Comment by nv-dlasalle** [comment]
Our error message needs work, but the total returned for device memory imply an error occurred in `cudaMemGetInfo`, and I think it is the same error you're getting the temp space size `101`, which is `cudaErrorInvalidDevice = 101`. Can run `nvidia-smi` to see if your GPU(s) are functioning correctly?

Although I don't think it's a cause of the error, you're currently passing in 1 as your chunk size for LZ4, which will not result in any compression. You should use something larger, usually 65536:

```
nvcomp::LZ4Compressor<uint32_t> compressor(
    uncompressed_data, uncompressed_count, 65536);
```

**Comment by shauryapatel1995** [comment]
This works now as suggested there as some issue with my nvidia driver installation. I reinstalled the drivers and that fixed that.
