### ISSUE TITLE
make files with "error: KeyValuePair is not a template"

### ISSUE THREAD

**Issue by postsql** [NVIDIA/nvcomp#16]
on Ubuntu 20.04 

after running cmake

```
hannu@P1G2:~/work/nvcomp/build$ cmake -DCUB_DIR=/usr/include/thrust/system/cuda/detail/ ..
...
Release build.
-- Finding CUB
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hannu/work/nvcomp/build
```
when trying to compile I get the following error:

```
(base) hannu@P1G2:~/work/nvcomp/build$ make
[  2%] Building NVCC (Device) object src/CMakeFiles/nvcomp.dir/nvcomp_generated_RunLengthEncodeGPU.cu.o
[  5%] Building NVCC (Device) object src/CMakeFiles/nvcomp.dir/nvcomp_generated_BitPackGPU.cu.o
[  7%] Building NVCC (Device) object src/CMakeFiles/nvcomp.dir/nvcomp_generated_CascadedCompressionGPU.cu.o
[ 10%] Building NVCC (Device) object src/CMakeFiles/nvcomp.dir/nvcomp_generated_CascadedDecompression.cu.o
/usr/include/thrust/system/cuda/detail/cub/device/../iterator/arg_index_input_iterator.cuh(120): error: KeyValuePair is not a template
...
```

with many more errors following

I am using CUDA as packaged with Ubuntu 

```
hannu@P1G2:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

**Comment by nv-dlasalle** [comment]
What version of thrust/cub do you have in /usr/include/thrust/system/cuda/detail/ ?

**Comment by postsql** [comment]
How do I find it out ?

in `/usr/include/thrust/version.h` it says `#define THRUST_VERSION 100905`

I could not find anything referring to version in `/usr/include/thrust/system/cuda/detail/cub/cub.cuh`

**Comment by nv-dlasalle** [comment]
@postsql Sorry for my delay in getting back to you. I have been able to reproduce this via a docker container using the ubuntu version you describe.

I have yet to determine the root-cause yet (whether it is in cub 1.9.5 or in nvcomp), but for now a workaround is to use the cub 1.9.10 release from github (or upgrade to cuda11):
```
git clone --depth=1 --branch=1.9.10 https://github.com/thrust/cub
cd build/
cmake -DCUB_DIR="${PWD}/../cub" ..
```

**Comment by mnicely** [comment]
We require CUDA >= 10.2
