### ISSUE TITLE
nvcompLZ4CompressAsync: Insufficient space for metadata

### ISSUE THREAD

**Issue by ludvigak** [NVIDIA/nvcomp#19]
When calling `nvcompLZ4CompressAsync` I get return code `nvcompErrorCudaError` and the message
```
Failed launch compression for batch: Insufficient space for metadata for item 0 : 0 / 48
```
but I'm having a really hard time figuring out what this means that I did wrong in my setup.

**Comment by nv-dlasalle** [comment]
@ludvigak Can you show all of your calls to nvcomp for this?

**Comment by ludvigak** [comment]
This was a mistake on my end - I had failed to see that `out_bytes` was used as both input and output, so I pointed out a zero-initialized value such that I could remember the maximum size given by `nvcompLZ4CompressGetOutputSize` that was used in allocation.
