### ISSUE TITLE
Compression Error

### ISSUE THREAD

**Issue by advanced373** [NVIDIA/nvcomp#27]
Hi,

I tried to run compress_async for 1000 files of about 100-200KB and I received this error ERROR: In nvcompBatchedLZ4CompressAsync(): Encountered Cuda Error: 700: 'an illegal memory access was encountered'. Anyone who encountered this problem?

Thanks,

**Comment by nv-dlasalle** [comment]
@advanced373 Can you share more about this case here (e.g., the inputs you gave to all of the functions calls)? As well as information about your GPU, CUDA, and compiler versions. Thanks!

**Comment by advanced373** [comment]
NVIDIA GeForce GTX 1050, Cuda 11.3, Compiler 11.0.
Here is my code.
[file.txt](https://github.com/NVIDIA/nvcomp/files/6251088/file.txt)

**Comment by advanced373** [comment]
@nv-dlasalle can you help me with an opinion.? I'm working on a project that depends on GPU Compression and I want to know if the problem is my GPU. Thank you very much.

**Comment by nv-dlasalle** [comment]
@advanced373 Sorry I haven't gotten back to you yet. In general, I think you're using the API correctly in that code snippet, though I haven't had the time to look at it rigorously. Your GPU I believe should work with nvcomp.

At this point, I would try simplifying the example to a single thread, as well as checking the return values of `cudaMemcpy` and `cudaMallocManaged` to ensure no errors are occurring there. It looks like you are also calling `cudaFree()` on your stream instead of `cudaStreamDestroy()`: https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__STREAM.html#group__CUDART__STREAM_1gfda584f1788ca983cb21c5f4d2033a62

**Comment by advanced373** [comment]
For some images, when compression size is higher than the uncompressed one, I received this error.  I found interesting that this problem is not always encountered. Here is the complete output received. Code is the following:

#include "cascaded.hpp"
#include "lz4.hpp"
#include <iostream>
using namespace std;
int getFileSize(FILE *in)
{
    fseek(in, 0, SEEK_END);
    int size = ftell(in);
    rewind(in);
    return size;
}
int main(int argc, char **argv)
{
    FILE *in = fopen(argv[1], "rb");
    if (in == NULL)
    {
        cout << "Error in reading file!" << endl;
        return 0;
    }
    unsigned char* uncompressed_value;
    int uncompressed_count = getFileSize(in);
     unsigned char *help = (unsigned char *)malloc(uncompressed_count);
    fread(help, uncompressed_count, 1, in);
    cudaError_t cudaErr;
    cudaMalloc((void**)&uncompressed_value, uncompressed_count);
    cudaMemcpy(uncompressed_value, help, uncompressed_count, cudaMemcpyHostToDevice);
    nvcomp::LZ4Compressor<unsigned char> compressor(
        uncompressed_value, uncompressed_count, 65356);
    const size_t temp_size = compressor.get_temp_size();
    void *temp_space;
    cudaErr = cudaMalloc(&temp_space, temp_size);
    if(cudaErr != cudaSuccess)
    {
        printf("Error!\n");
        return 0;
    }
    size_t output_size = compressor.get_max_output_size(
        temp_space, temp_size);
    void *output_space;
    cudaErr =  cudaMalloc(&output_space, output_size);
     if(cudaErr != cudaSuccess)
    {
        printf("Eroare in alocare outputSize!\n");
        return 0;
    }
    cudaStream_t stream;
    cudaErr = cudaStreamCreate(&stream);
     if(cudaErr != cudaSuccess)
    {
        printf("Eroare in creare Stream!\n");
        return 0;
    }
    nvcompError_t status;
    printf("%d %d\n",output_size, temp_size);
    compressor.compress_async(temp_space,
                              temp_size, output_space, &output_size, stream);
    printf("%d\n",output_size);
}

 ERROR: In nvcompCascadedCompressAsync(): Encountered Cuda Error: 700: 'an illegal memory access was encountered': CudaUtils::copy_async(dst, src, count, kind, stream).
terminate called after throwing an instance of 'nvcomp::NVCompException'
  what():  nvcompCascadedCompressAsync() failed : code=10.
Aborted

Thank you very much for your help.

**Comment by advanced373** [comment]
I have also another question. This library can be used in Windows?

**Comment by advanced373** [comment]
Hi,

I got this error.
LZ4CompressionKernels.cu:730: block: [0,0,0], thread: [31,0,0] Assertion `match_location < pos` failed.
ERROR: In nvcompBatchedLZ4CompressAsync(): Encountered Cuda Error: 710: 'device-side assert triggered': CudaUtils::copy_async(dst, src, count, kind, stream).
CHECK FAILED: C:\Users\mihai\source\repos\Nvcomp\Nvcomp\nvcomp\src\LZ4.cpp:187

Thanks,

**Comment by nv-dlasalle** [comment]
@advanced373 Thanks for providing more details. This looks like a bug in our code. Are you able to share the file/data which you were compressing that resulted in this error? Thanks!

**Comment by advanced373** [comment]
Sure. This is my code.
#include <cascaded.hpp>
#include <lz4.hpp>
#include <iostream>
#include <driver_types.h>
#include <cuda_runtime.h>
using namespace std;
int getFileSize(FILE* in)
{
    fseek(in, 0, SEEK_END);
    int size = ftell(in);
    rewind(in);
    return size;
}
int main(int argc, char** argv)
{
    FILE* in = fopen(argv[1], "rb");
    if (in == NULL)
    {
        cout << "Error in reading file!" << endl;
        return 0;
    }
    unsigned char* uncompressed_value;
    int uncompressed_count = getFileSize(in);
    unsigned char* help = (unsigned char*)malloc(uncompressed_count);
    fread(help, uncompressed_count, 1, in);
    cudaError_t cudaErr;
    printf("%d", uncompressed_count);
    cudaErr = cudaMalloc((void**)&uncompressed_value, uncompressed_count);
    if (cudaErr != cudaSuccess)
    {
        printf("Error!\n");
        return 0;
    }
    cudaErr = cudaMemcpy(uncompressed_value, help, uncompressed_count, cudaMemcpyHostToDevice);
    if (cudaErr != cudaSuccess)
    {
        printf("Error!\n");
        return 0;
    }
    nvcomp::LZ4Compressor<unsigned char> compressor(
        uncompressed_value, uncompressed_count, 65536);
    const size_t temp_size = compressor.get_temp_size();
    void* temp_space;
    cudaErr = cudaMalloc(&temp_space, temp_size);
    if (cudaErr != cudaSuccess)
    {
        printf("Error!\n");
        return 0;
    }
    size_t output_size = compressor.get_max_output_size(
        temp_space, temp_size);
    void* output_space;
    cudaErr = cudaMalloc(&output_space, output_size);
    if (cudaErr != cudaSuccess)
    {
        printf("Eroare in alocare outputSize!\n");
        return 0;
    }
    cudaStream_t stream;
    cudaErr = cudaStreamCreate(&stream);
    if (cudaErr != cudaSuccess)
    {
        printf("Eroare in creare Stream!\n");
        return 0;
    }
    nvcompError_t status;
    printf("%d %d\n", output_size, temp_size);
    compressor.compress_async(temp_space,
        temp_size, output_space, &output_size, stream);
    printf("%d\n", output_size);
}
And image that i tested.
![cat](https://user-images.githubusercontent.com/53189285/113941891-a3312780-9808-11eb-971e-7f260c686146.jpg)

**Comment by nv-dlasalle** [comment]
@advanced373 I managed to track down the bug to our workaround for emulating `__match_any_sync()` on Pascal. It looks like I introduced this bug a few months ago, and unfortunately our testing has been focused on architectures after Pascal and missed this.

Here is a patch for you to test out until we get a new version out with this fix. Thanks for finding this issue!
```
diff --git a/src/LZ4CompressionKernels.cu b/src/LZ4CompressionKernels.cu
index eae235c..4d88002 100644
--- a/src/LZ4CompressionKernels.cu
+++ b/src/LZ4CompressionKernels.cu
@@ -121,10 +121,20 @@ inline __device__ int warpMatchAny(const int participants, T val)
   int mask = 0;

   // full search
+  __shared__ T values[32];
   assert(blockDim.x == 32);
-  for (int d = 1; d < 32; ++d) {
-    const int nbr_id = (threadIdx.x + d) & 31;
-    mask |= (val == __shfl_sync(participants, val, nbr_id)) << nbr_id;
+  assert(blockDim.y == 1);
+  if ((1 << threadIdx.x) & participants) {
+    values[threadIdx.x] = val;
+    __syncwarp(participants);
+    for (int d = 0; d < 32; ++d) {
+      const int nbr_id = (threadIdx.x + d) & 31;
+      if ((1 << nbr_id) & participants) {
+        const T nbr_val = values[nbr_id];
+        mask |= (val == nbr_val) << nbr_id;
+      }
+    }
+    __syncwarp(participants);
   }

   return mask;
```

**Comment by nv-dlasalle** [comment]
@advanced373 This should be fixed in the latest version now (https://github.com/NVIDIA/nvcomp/releases/tag/v1.2.3). Please let me know if see any more issues. Thanks!
