### ISSUE TITLE
nvcomp 2.0 release?

### ISSUE THREAD

**Issue by oscarbg** [NVIDIA/nvcomp#28]
there is a new blog post, saying it's already available:
https://developer.nvidia.com/blog/nvcomp-v2-0-0-now-available-with-new-compressors/

**Comment by fwyzard** [comment]
Looks like the full nvCOMP 2.0 library is no longer an open source project.
From the [nvCOMP NVIDIA Developer page](https://developer.nvidia.com/nvcomp):

> ![image](https://user-images.githubusercontent.com/4069793/116818876-d8156d80-ab6d-11eb-87df-557a9a99c8e6.png)

**Comment by nv-dlasalle** [comment]
@oscarbg My apologies for the confusion this has caused. We're still working on fixing a few bugs discovered at the last moment before pushing out release 2.0. We should have it here on github in the next few days.

@fwyzard For the 2.0 release, we are adding support for two new proprietary compressors and a new open source compressor. The existing compressors' implementations (LZ4 and Cascaded) remain open source.

**Comment by nv-dlasalle** [comment]
The 2.0 release has now been pushed. Sorry for the delay!

**Comment by oscarbg** [comment]
Hi,
just a question, I'm downloading "nvCOMP extensions" and don't see a Windows x64 download.. it's expected Win platform to be supported for exts eventually?
thanks!
