### ISSUE TITLE
CMake improvements for use in other projects

### ISSUE THREAD

**Issue by devavret** [NVIDIA/nvcomp#32]
In order to use external projects in cuDF, certain improvements to CMakeLists are needed/desired.
1. An install target. 
2. Using build interface to install include directory
3. Make including/linking CUB, bitcomp, and gdeflate private
4. Guard tests, benchmarks, and examples so that they can be turned off and are not built when included by another project.

CC @robertmaynard.

**Comment by nv-dlasalle** [comment]
These were added in 2.0.0.
