### ISSUE TITLE
Snappy decompression doesn't provide uncompressed size

### ISSUE THREAD

**Issue by chuckseberino** [NVIDIA/nvcomp#35]
The current implementation of `nvcompBatchedSnappyDecompressAsync` doesn't allow retrieval of the actual size of uncompressed bytes. The code [here](https://github.com/NVIDIA/nvcomp/blob/main/src/SnappyBatch.cpp#L99-L103) sets a nullptr as the input to `gpu_unsnap`. I naively thought that `device_out_bytes` would be updated, but apparently not.

How would one know the original, uncompressed size of their input is? This implementation seems geared towards a contrived use case, where the user has apriori knowledge of the result.

**Comment by nsakharnykh** [comment]
Hi @chuckseberino, we’re in the process of updating the 2.0 API to have a way to output the uncompressed size. Please stay tuned and look for a new dev branch with the changes over the next month.

**Comment by mnicely** [comment]
v2.1 has been released. @chuckseberino do you mind checking if it solves your issue?
