### ISSUE TITLE
Unified memory in nvcomp question

### ISSUE THREAD

**Issue by benjha** [NVIDIA/nvcomp#39]
Hi nvcomp team,

Does nvcomp uses cuda unified memory or any other mechanism to deal with files larger than GPU memory ?

Thanks,

**Comment by nv-dlasalle** [comment]
Hi @benjha,

nvCOMP does not allocate GPU memory itself, and instead relies on the calling code to allocate GPU memory. There are several requirements that different memory passed into the API is accessible either from the CPU or GPU. You can pass in unified memory to these APIs and they will work fine. You may see decreased performance if page migration needs to take place (as is generally the case for unified memory).

Does this answer your question?

**Comment by benjha** [comment]
Yes, thanks!
