### ISSUE TITLE
Snappy decompressor unable to decompress chunk

### ISSUE THREAD

**Issue by devavret** [NVIDIA/nvcomp#40]
NVComp's snappy decompressor in branch-2.1-dev is unable to decompress the attached chunk. The last 40 bytes are unwritten.

[problem_piece.snappy.zip](https://github.com/NVIDIA/nvcomp/files/7048601/problem_piece.snappy.zip)

**Comment by nsakharnykh** [comment]
Fixed with 3a12516afdeab4ace01298031757f84b8dda81b7
