### ISSUE TITLE
Requested clarifications on type of compression for supported methodss

### ISSUE THREAD

**Issue by pkoosha** [NVIDIA/nvcomp#43]
Hi,

I am a bit lost which methods are lossy and which ones are lossless. Another question is that if all of them support double precision data compression or not. Could you please provide some info about them?
Also, what is the compression throughput for each type?

Thanks,
Pouya

**Comment by nsakharnykh** [comment]
Hi Pouya, all methods are lossless. README contains a compression throughput chart for cascaded, LZ4 and Snappy. We’ll be updating perf charts soon with more recent results.

**Comment by pkoosha** [comment]
Thanks for the comment. So the file you have CPU in their name like "gdeflate_cpu_compression", do they run on CPU or GPU? I am very confused by the naming of it.

**Comment by nv-dlasalle** [comment]
That example performs the compression with the CPU, then copies the data to GPU memory, and uses the GPU to decompress it.

The LZ4 examples are similarly named, where the CPU is used to compress the data and the GPU decompresses the data (https://github.com/NVIDIA/nvcomp/blob/main/examples/lz4_cpu_compression.cu) or vice versa (https://github.com/NVIDIA/nvcomp/blob/main/examples/lz4_cpu_decompression.cu).

**Comment by pkoosha** [comment]
Thanks for the clarification. I was wondering if there are any benchmarks that uses GPU for both compress and decompress?
Could you explain why the GPU is not used for compression?

**Comment by mnicely** [comment]
We removed the benchmarks he's referring to and now just have a benchmark for LLIF / HLIF
