### ISSUE TITLE
[FEA] Support Bitcomp on Jetson

### ISSUE THREAD

**Issue by limitz** [NVIDIA/nvcomp#48]
I would like to be able to use Bitcomp on the Jetson Xavier AGX, but I can only find the download for x86_64. Is that possible?
Ideally I would like to install and run nvcomp and the proprietary compression algorithms on the Jetson. If this requires some kind of license I am still interested.

I tried some of alternative compression methods, but Bitcomp seems to be the only algorithm that makes a dent in the filesize of the type of data I capture, 12 bit x 16 channel raw hyperspectral (highly correlated), in blocks on 4x4xuint16, so with a 64bit "stride" on each row. 

Thanks.

**Comment by nsakharnykh** [comment]
We’re planning to release binaries for Jetson in 2.3 release

**Comment by smaximz** [comment]
I still can not find version for Jetson at download page.
Is there any version that can run on Jetson (Orin for example)?
