### ISSUE TITLE
[BUG] Can't be compiled on Windows 

### ISSUE THREAD

**Issue by BarabashkaD** [NVIDIA/nvcomp#51]
1) CMake file can't be configurate 
CMake Error at CMakeLists.txt:186 (install):
  install FILES given no DESTINATION!

2) after fixing first issue by adding slash ${CMAKE_INSTALL_INCLUDEDIR}/
still can't be compiled because of error on all .CU files
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xutility(1309): error : expected a "("
1>          detected during instantiation of "void std::_Adl_verify_range(const _Iter &, const _Sentinel &) [with _Iter=const char *, _Sentinel=const char *]"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xlocale(1990): here

**Comment by nsakharnykh** [comment]
A lot of Windows build issues will be fixed in 2.2 release - please retry then and let us know if the issue still exists. We will be also shipping Windows binaries starting from 2.2.
