### ISSUE TITLE
[QST] Compress on CPU then decompress on GPU, and compress on GPU then decompress on CPU

### ISSUE THREAD

**Issue by ucasfl** [NVIDIA/nvcomp#56]
**What is your question?**
Hi, currently, I need to to a work like the issue title descripted, and I just use LZ4 algorithm. But I found something very strange, for example, the compressed output size with nvcomp is a little larger than the compressed output size with https://github.com/lz4/lz4 for same data(100 bytes in my test), I get the compressed output size with method `nvcomp_manager.get_compressed_output_size(cmp_buffer)`.

I don't understand why this happened, and does my idea is ok to implement with nvcomp?

**Comment by ucasfl** [comment]
> **What is your question?** Hi, currently, I need to to a work like the issue title descripted, and I just use LZ4 algorithm. But I found something very strange, for example, the compressed output size with nvcomp is a little larger than the compressed output size with https://github.com/lz4/lz4 for same data(100 bytes in my test), I get the compressed output size with method `nvcomp_manager.get_compressed_output_size(cmp_buffer)`.
> 
> I don't understand why this happened, and does my idea is ok to implement with nvcomp?

I found there is a common header in the beginning of the compressed buffer, from the common header, I can get the compressed data size, but the data size is still four bytes larger than the compressed data size by lz4, I don't know why.

**Comment by ucasfl** [comment]
> > **What is your question?** Hi, currently, I need to to a work like the issue title descripted, and I just use LZ4 algorithm. But I found something very strange, for example, the compressed output size with nvcomp is a little larger than the compressed output size with https://github.com/lz4/lz4 for same data(100 bytes in my test), I get the compressed output size with method `nvcomp_manager.get_compressed_output_size(cmp_buffer)`.
> > I don't understand why this happened, and does my idea is ok to implement with nvcomp?
> 
> I found there is a common header in the beginning of the compressed buffer. From the common header, I can get the compressed data size, but the data size is still four bytes larger than the compressed data size by lz4, I don't know why.

Because there are `LZ4FormatSpecHeader` after common header.

**Comment by ucasfl** [comment]
How can I copy all the compressed data without metadata like headers?

**Comment by ucasfl** [comment]
Looks like the algorithm LZ4 implement is different from https://github.com/lz4/lz4, because for the same data, I checked the   compressed output data both of them, and they are different.

**Comment by nv-dlasalle** [comment]
@ucasfl LZ4 on the GPU will produce different compressed output as it has a different algorithm for finding matches. Were you finding that data compressed on the GPU was not decompressible correctly the CPU lz4 implementation?

**Comment by ucasfl** [comment]
> @ucasfl LZ4 on the GPU will produce different compressed output as it has a different algorithm for finding matches. Were you finding that data compressed on the GPU was not decompressible correctly the CPU lz4 implementation?

Yes.

**Comment by ucasfl** [comment]
Currently, I following the lowlevel api in `lz4_cpu_compression.cu` and `lz4_cpu_decompression.cu` can do compress and decompress between CPU and GPU.

**Comment by nv-dlasalle** [comment]
Thanks @ucasfl, this sounds like a bug. Can you provide information such what dataset you see this on, the CUDA version, the host compiler version (e.g., gcc 9.3.0) and on what GPU?

**Comment by nv-dlasalle** [comment]
See here for the LZ4 block: https://github.com/lz4/lz4/blob/dev/doc/lz4_Block_format.md
and here for the LZ4 frame: https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md

**Comment by ucasfl** [comment]
> See here for the LZ4 block: https://github.com/lz4/lz4/blob/dev/doc/lz4_Block_format.md and here for the LZ4 frame: https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md

OK, thanks
