### ISSUE TITLE
[QST] Run Benchmarks

### ISSUE THREAD

**Issue by CupidLiuTian** [NVIDIA/nvcomp#64]
Hello, when i complie the benchmarks from the project who clone from the github, the package bitcomp,ans and GDeflate are not founded, this situation lead to some test programs are not build, such as benchmark_bitcomp_chunked and benchmark_ans_chunked.So where can i get the package gdeflate,bitcomp and ans. Or How can i build the complete project.Thanks!

**Comment by mnicely** [comment]
With nvCOMP v2.3, all compressors can be downloaded from [DevZone](https://github.com/NVIDIA/nvcomp#download). 

You can still clove v2.2 from GitHub, but Bitcomp, ANS, GDeflate are only availabe on DevZone.

**Comment by CupidLiuTian** [comment]
> With nvCOMP v2.3, all compressors can be downloaded from [DevZone](https://github.com/NVIDIA/nvcomp#download).
> 
> You can still clone v2.2 from GitHub, but Bitcomp, ANS, GDeflate are only availabe on DevZone.

Thanks for your reply.Noew i get the extension of gdeflate,bitcomp and ans from the dev history version of v2.2, i can build all the benchmarks and test program. But when i run the benchmark_hlif with cascaded and the input file was larger,this will occur an error which tell me cudaStreamSynchronize(stream)" with 700.  Also when i used the version 2.3 and run the same benchmark who does not occur the error. So does the v2.2 has bugs and fixed in the version v2.3?

**Comment by mnicely** [comment]
I'm not aware of any bugs related to that functionality.
