### ISSUE TITLE
[QST] Why isn't there an API to decompress data as one single chunk ? (ZSTD) 

### ISSUE THREAD

**Issue by shreer1998** [NVIDIA/nvcomp#65]
I could see that the current API to decompress the data compressed by ZSTD is nvcompBatchedZstdDecompressAsync. 
Are there any plans to provide an API to decompress data as one single chunk (entire data is one single batch) ? 
If yes, when can we expect it and if it's no, plans what's reason behind it ?

**Comment by nsakharnykh** [comment]
@shreer1998 do you have a use case for the single chunk decompression on the GPU? For zstd or other formats. Please let us know. So far we’ve been focusing on supporting Apache Parquet/ORC type of files that usually have many chunks, so we’ve been prioritizing the batched interface.

**Comment by eschmidt-nvidia** [comment]
Hi @shreer1998, 

Can you help us understand why you can't split the data into many smaller chunks on the CPU? I.e. through multiple calls to the CPU compressor (possibly even with many threads?) 

Note, there is no minimum batch size in the `nvcompBatchedZstdDecompressAsync` API, so you can call it with 1 chunk (up to 2 GB in size). 

Unfortunately, the performance will be slow with such a single chunk.

**Comment by shreer1998** [comment]
Hello, @eschmidt-nvidia.

Thanks for the response. I didn't have the option to tweak the CPU zstd compression into batched compression as the CPU part was frozen for some reason. Given the fact that chunk sizes can be up to 2GB, it solves my issue for now. I thought it was restricted to 64KB.
