### ISSUE TITLE
Deep Learning 

### ISSUE THREAD

**Issue by johnnynunez** [NVIDIA/nvcomp#71]
I think that would be interesting if the GPUs had hardware dedicated to data compression and decompression. It would be incredible in tools such as deep learning where there is constantly a large volume of data in transfer. But now, Is it possible to implement it in deep learning frameworks like pytorch? I see new API direct storage features https://devblogs.microsoft.com/directx/directstorage-1-1-coming-soon/

**Comment by nsakharnykh** [comment]
hi @johnnynunez, do you have any particular use case in mind for fast compression/decompression for deep learning?

**Comment by johnnynunez** [comment]
> hi @johnnynunez, do you have any particular use case in mind for fast compression/decompression for deep learning?

In the hypothetical case that all my preprocessing is done offline. Wouldn't it be possible to load the batches from the SSD in compressed form?

**Comment by johnnynunez** [comment]
> hi @johnnynunez, do you have any particular use case in mind for fast compression/decompression for deep learning?



> hi @johnnynunez, do you have any particular use case in mind for fast compression/decompression for deep learning?

In the hypothetical case that all my preprocessing is done offline. Wouldn't it be possible to load the batches from the SSD in compressed form?

**Comment by johnnynunez** [comment]
> hi @johnnynunez, do you have any particular use case in mind for fast compression/decompression for deep learning?

In the hypothetical case that all my preprocessing is done offline. Wouldn't it be possible to load the batches from the SSD in compressed form?

**Comment by nsakharnykh** [comment]
@johnnynunez for loading data directly from SSD bypassing the CPU you need to use GPUDirect Storage (GDS), it's orthogonal to the compression, and we have an example of using nvCOMP with GDS https://github.com/NVIDIA/nvcomp/blob/main/examples/nvcomp_gds.cu

The link you referenced introduces a new format GDeflate, we support both compression and decompression of GDeflate format in nvCOMP on the GPU.

BTW, is your platform Windows or Linux?

**Comment by johnnynunez** [comment]
> @johnnynunez for loading data directly from SSD bypassing the CPU you need to use GPUDirect Storage (GDS), it's orthogonal to the compression, and we have an example of using nvCOMP with GDS https://github.com/NVIDIA/nvcomp/blob/main/examples/nvcomp_gds.cu
> 
> The link you referenced introduces a new format GDeflate, we support both compression and decompression of GDeflate format in nvCOMP on the GPU.
> 
> BTW, is your platform Windows or Linux?

Linux
