### ISSUE TITLE
[BUG] Need to wrap cub:: and thrust:: namespace in nvcomp namespace 

### ISSUE THREAD

**Issue by lilohuang** [NVIDIA/nvcomp#72]
**Describe the bug**

Download **nvcomp_2.4.1_x86_64_11.x.tgz** from NVIDIA website, and dump symbols from NVCOMP shared objects with nm. I still can see a lot cub:: and thrust:: functions are not wrapped in nvcomp namespace. Please refer to https://github.com/NVIDIA/thrust/issues/1401 to recompile NVCOMP shared objects to prevent crash in CUDA 11.

e.g. 
<pre>
bash-4.2$ nm -CD libnvcomp.so | grep cub
000000000002df70 W void cub::EmptyKernel<void>()
0000000000035950 W void nvcomp::cub::EmptyKernel<void>()
</pre>

**Expected behavior**
All cub:: and thrust:: functions must be wrapped in nvcomp namespace.

**Comment by ndickson-nvidia** [comment]
Thanks for pointing this out and for linking to a page containing the solution!  From [the post](https://github.com/NVIDIA/thrust/issues/1401#issuecomment-882805440), it looks like it should be fairly straightforward to address, but I'll see what I can do.

**Comment by lilohuang** [comment]
This is of course needed and cannot be closed.

**Comment by ndickson-nvidia** [comment]
Thanks for pinging this again!  It ended up being not quite as simple as it looked at first, and somehow, some other people using both nvCOMP and cub/thrust weren't running into the same issue, so it fell by the wayside for a bit.  I'll try asking the person who gave the originally suggested fix.  There's probably something simple that I missed.

**Comment by ndickson-nvidia** [comment]
Yep.  There were a couple simple things that I'd missed.  I have a change that seems to work, and it should be in a release fairly soon.

**Comment by lilohuang** [comment]
@ndickson-nvidia thanks for your feedback. :)

**Comment by ndickson-nvidia** [comment]
nvCOMP 2.5.1 is now out and should hopefully fix this, but please let us know if it doesn't, and I'll try to investigate further.  Thanks again for pointing this out!
