### ISSUE TITLE
GitHub releases out of sync with git tags

### ISSUE THREAD

**Issue by EwoutH** [NVIDIA/nvcomp#74]
The GitHub releases are out of sync with the git tags. Currently, the latest [GitHub release](https://github.com/NVIDIA/nvcomp/releases) is [v2.2.0](https://github.com/NVIDIA/nvcomp/releases/tag/v2.2.0), while the latest [git tag](https://github.com/NVIDIA/nvcomp/tags) is [v2.4.1](https://github.com/NVIDIA/nvcomp/releases/tag/v2.4.1).

This can be confusing, so it would be nice if those two were brought in sync again.

**Comment by ndickson-nvidia** [comment]
Thanks for pointing this out!  The GitHub releases have now been updated.
