### ISSUE TITLE
[QST]

### ISSUE THREAD

**Issue by jedwards4b** [NVIDIA/nvcomp#79]
**What is your question?**

Has anyone created an hdf5 filter using nvCOMP?

**Comment by akshaysubr** [comment]
@jedwards4b The only ones we are aware of is the ParallelIO team that you probably are very familiar with already.

Could you describe your use case a bit more? If it is read heavy, there is another potential path. We are looking at the [zarr](https://github.com/zarr-developers/zarr-python/tree/main/zarr) format and you can actually make HDF5 datasets look like zarr using a tool called [kerchunk](https://github.com/fsspec/kerchunk) without actually transcoding the dataset. Would this be something you are interested in?

**Comment by jedwards4b** [comment]
We did this for an Nvidia hackathon last week at ncar.  Our application is write not read heavy.  Our primary issue now is that our datasets need to be portable and so we would like,for example, a file zstandard compressed using nvcomp to be able to be decompressed by the default zstandard library.  Not quite sure how to manage that yet.

**Comment by ndickson-nvidia** [comment]
Issue #80 seems to subsume this one, so I'm closing this one.
